# Generated by Django 4.0.6 on 2022-07-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follower',
            new_name='followers',
        ),
    ]
