# Generated by Django 4.0.6 on 2022-07-29 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_followers_userfollower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollower',
            name='user',
        ),
        migrations.AddField(
            model_name='userfollower',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
