# Generated by Django 4.0.6 on 2022-07-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_userfollower_user_userfollower_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollower',
            unique_together={('follower', 'following')},
        ),
    ]
