# Generated by Django 4.0.6 on 2022-07-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_userfollower_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollower',
            unique_together=set(),
        ),
    ]
