# Generated by Django 4.1.1 on 2022-10-04 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_alter_settings_currency_alter_settings_reset_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('ILS', 'ILS'), ('XUA', 'XUA'), ('RHD', 'RHD'), ('LYD', 'LYD'), ('CUC', 'CUC'), ('ALK', 'ALK'), ('ADP', 'ADP'), ('KPW', 'KPW'), ('LVL', 'LVL'), ('RWF', 'RWF'), ('MKN', 'MKN'), ('BYN', 'BYN'), ('BRE', 'BRE'), ('XFO', 'XFO'), ('USS', 'USS'), ('XRE', 'XRE'), ('ZRN', 'ZRN'), ('GHS', 'GHS'), ('PEI', 'PEI'), ('MTP', 'MTP'), ('ZWL', 'ZWL'), ('MAF', 'MAF'), ('PAB', 'PAB'), ('UAK', 'UAK'), ('ARL', 'ARL'), ('PLN', 'PLN'), ('CUP', 'CUP'), ('ITL', 'ITL'), ('DDM', 'DDM'), ('NLG', 'NLG'), ('SRG', 'SRG'), ('GRD', 'GRD'), ('NGN', 'NGN'), ('AUD', 'AUD'), ('MZM', 'MZM'), ('TWD', 'TWD'), ('XBA', 'XBA'), ('TPE', 'TPE'), ('BGN', 'BGN'), ('COU', 'COU'), ('GQE', 'GQE'), ('RUR', 'RUR'), ('PES', 'PES'), ('XDR', 'XDR'), ('CHF', 'CHF'), ('AWG', 'AWG'), ('GNF', 'GNF'), ('ETB', 'ETB'), ('JMD', 'JMD'), ('KRH', 'KRH'), ('SCR', 'SCR'), ('LSL', 'LSL'), ('BIF', 'BIF'), ('YUM', 'YUM'), ('HRK', 'HRK'), ('BAM', 'BAM'), ('KWD', 'KWD'), ('MGF', 'MGF'), ('BMD', 'BMD'), ('ARM', 'ARM'), ('UYI', 'UYI'), ('ISK', 'ISK'), ('ILR', 'ILR'), ('ALL', 'ALL'), ('ANG', 'ANG'), ('NZD', 'NZD'), ('BRB', 'BRB'), ('CVE', 'CVE'), ('TJS', 'TJS'), ('MXN', 'MXN'), ('SDD', 'SDD'), ('ZRZ', 'ZRZ'), ('MVR', 'MVR'), ('VNN', 'VNN'), ('WST', 'WST'), ('BDT', 'BDT'), ('BRZ', 'BRZ'), ('MTL', 'MTL'), ('ZMK', 'ZMK'), ('MKD', 'MKD'), ('NIO', 'NIO'), ('XBD', 'XBD'), ('SAR', 'SAR'), ('BGL', 'BGL'), ('DKK', 'DKK'), ('CLP', 'CLP'), ('BAD', 'BAD'), ('SIT', 'SIT'), ('TTD', 'TTD'), ('BND', 'BND'), ('KES', 'KES'), ('NPR', 'NPR'), ('XPT', 'XPT'), ('MYR', 'MYR'), ('PGK', 'PGK'), ('CLF', 'CLF'), ('SGD', 'SGD'), ('XAG', 'XAG'), ('GEL', 'GEL'), ('LUL', 'LUL'), ('AFN', 'AFN'), ('LTT', 'LTT'), ('COP', 'COP'), ('GMD', 'GMD'), ('AOK', 'AOK'), ('TJR', 'TJR'), ('BOP', 'BOP'), ('FJD', 'FJD'), ('QAR', 'QAR'), ('ZAL', 'ZAL'), ('TMT', 'TMT'), ('XCD', 'XCD'), ('XFU', 'XFU'), ('STD', 'STD'), ('BYB', 'BYB'), ('ECS', 'ECS'), ('VES', 'VES'), ('MAD', 'MAD'), ('XEU', 'XEU'), ('EUR', 'EUR'), ('DOP', 'DOP'), ('AOA', 'AOA'), ('ARS', 'ARS'), ('CNH', 'CNH'), ('DEM', 'DEM'), ('IEP', 'IEP'), ('SYP', 'SYP'), ('BUK', 'BUK'), ('XTS', 'XTS'), ('BAN', 'BAN'), ('UAH', 'UAH'), ('XAU', 'XAU'), ('BZD', 'BZD'), ('YUR', 'YUR'), ('ESP', 'ESP'), ('GYD', 'GYD'), ('VUV', 'VUV'), ('CDF', 'CDF'), ('BOL', 'BOL'), ('DJF', 'DJF'), ('BTN', 'BTN'), ('BSD', 'BSD'), ('MOP', 'MOP'), ('ZMW', 'ZMW'), ('GWE', 'GWE'), ('MDL', 'MDL'), ('MXP', 'MXP'), ('PTE', 'PTE'), ('NAD', 'NAD'), ('KRW', 'KRW'), ('TRY', 'TRY'), ('LTL', 'LTL'), ('TOP', 'TOP'), ('CSK', 'CSK'), ('CSD', 'CSD'), ('SKK', 'SKK'), ('MZE', 'MZE'), ('AON', 'AON'), ('CHW', 'CHW'), ('VEF', 'VEF'), ('BOV', 'BOV'), ('OMR', 'OMR'), ('GNS', 'GNS'), ('ROL', 'ROL'), ('AZM', 'AZM'), ('SOS', 'SOS'), ('TRL', 'TRL'), ('PYG', 'PYG'), ('AED', 'AED'), ('ESA', 'ESA'), ('YDD', 'YDD'), ('MRU', 'MRU'), ('LVR', 'LVR'), ('SZL', 'SZL'), ('FRF', 'FRF'), ('BGO', 'BGO'), ('VND', 'VND'), ('CHE', 'CHE'), ('CYP', 'CYP'), ('LRD', 'LRD'), ('UYU', 'UYU'), ('BWP', 'BWP'), ('CNY', 'CNY'), ('SVC', 'SVC'), ('ECV', 'ECV'), ('EEK', 'EEK'), ('MGA', 'MGA'), ('ARP', 'ARP'), ('SRD', 'SRD'), ('VED', 'VED'), ('RUB', 'RUB'), ('SDP', 'SDP'), ('BHD', 'BHD'), ('BOB', 'BOB'), ('UYP', 'UYP'), ('KGS', 'KGS'), ('MNT', 'MNT'), ('PLZ', 'PLZ'), ('SBD', 'SBD'), ('TZS', 'TZS'), ('ILP', 'ILP'), ('YUN', 'YUN'), ('ZAR', 'ZAR'), ('LUC', 'LUC'), ('MZN', 'MZN'), ('BRR', 'BRR'), ('MDC', 'MDC'), ('FIM', 'FIM'), ('GWP', 'GWP'), ('HRD', 'HRD'), ('USN', 'USN'), ('FKP', 'FKP'), ('ATS', 'ATS'), ('KRO', 'KRO'), ('MWK', 'MWK'), ('HTG', 'HTG'), ('SDG', 'SDG'), ('ZWR', 'ZWR'), ('ZWD', 'ZWD'), ('HKD', 'HKD'), ('LAK', 'LAK'), ('XAF', 'XAF'), ('EGP', 'EGP'), ('MXV', 'MXV'), ('UGS', 'UGS'), ('MVP', 'MVP'), ('XPD', 'XPD'), ('SHP', 'SHP'), ('CAD', 'CAD'), ('RON', 'RON'), ('YUD', 'YUD'), ('BRC', 'BRC'), ('CZK', 'CZK'), ('SUR', 'SUR'), ('PHP', 'PHP'), ('ARA', 'ARA'), ('AOR', 'AOR'), ('HNL', 'HNL'), ('SSP', 'SSP'), ('IDR', 'IDR'), ('MUR', 'MUR'), ('JOD', 'JOD'), ('USD', 'USD'), ('AFA', 'AFA'), ('AZN', 'AZN'), ('KMF', 'KMF'), ('UGX', 'UGX'), ('GEK', 'GEK'), ('GBP', 'GBP'), ('PEN', 'PEN'), ('LBP', 'LBP'), ('BYR', 'BYR'), ('YER', 'YER'), ('BRN', 'BRN'), ('CLE', 'CLE'), ('ISJ', 'ISJ'), ('BEF', 'BEF'), ('ESB', 'ESB'), ('MLF', 'MLF'), ('BEL', 'BEL'), ('BGM', 'BGM'), ('LUF', 'LUF'), ('NOK', 'NOK'), ('MMK', 'MMK'), ('BBD', 'BBD'), ('XXX', 'XXX'), ('IRR', 'IRR'), ('TMM', 'TMM'), ('LKR', 'LKR'), ('XBC', 'XBC'), ('AMD', 'AMD'), ('XPF', 'XPF'), ('GTQ', 'GTQ'), ('PKR', 'PKR'), ('KYD', 'KYD'), ('INR', 'INR'), ('JPY', 'JPY'), ('BRL', 'BRL'), ('IQD', 'IQD'), ('KZT', 'KZT'), ('UZS', 'UZS'), ('VEB', 'VEB'), ('CRC', 'CRC'), ('XSU', 'XSU'), ('KHR', 'KHR'), ('THB', 'THB'), ('UYW', 'UYW'), ('TND', 'TND'), ('DZD', 'DZD'), ('ERN', 'ERN'), ('SLL', 'SLL'), ('RSD', 'RSD'), ('GIP', 'GIP'), ('BEC', 'BEC'), ('XOF', 'XOF'), ('SEK', 'SEK'), ('HUF', 'HUF'), ('MRO', 'MRO'), ('GHC', 'GHC'), ('MCF', 'MCF'), ('NIC', 'NIC'), ('STN', 'STN'), ('XBB', 'XBB'), ('CNX', 'CNX'), ('SLE', 'SLE')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='settings',
            name='reset_day',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
