# Generated by Django 4.1.1 on 2022-12-05 04:05

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0008_alter_budget_budget_amount_alter_settings_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FD', 'Food & Drinks'), ('SG', 'Shopping'), ('RT', 'Rent'), ('TL', 'Travel'), ('SS', 'Sports'), ('IT', 'Internet'), ('IS', 'Investments'), ('ET', 'Entertainment'), ('SY', 'Study'), ('VE', 'Vehicle'), ('TN', 'Transportation'), ('GS', 'Groceries'), ('KS', 'Kids'), ('GT', 'Gifts'), ('GL', 'General'), ('FL', 'Fuel'), ('HS', 'Holidays')], default=builtins.all, max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('DJF', 'DJF'), ('BOP', 'BOP'), ('AMD', 'AMD'), ('YUN', 'YUN'), ('LUF', 'LUF'), ('KYD', 'KYD'), ('MWK', 'MWK'), ('KMF', 'KMF'), ('CNY', 'CNY'), ('ECS', 'ECS'), ('GHS', 'GHS'), ('YDD', 'YDD'), ('CZK', 'CZK'), ('INR', 'INR'), ('LSL', 'LSL'), ('CSD', 'CSD'), ('DZD', 'DZD'), ('HKD', 'HKD'), ('MXN', 'MXN'), ('KHR', 'KHR'), ('VND', 'VND'), ('CNX', 'CNX'), ('XAG', 'XAG'), ('YUR', 'YUR'), ('SOS', 'SOS'), ('NLG', 'NLG'), ('SSP', 'SSP'), ('BAD', 'BAD'), ('ISJ', 'ISJ'), ('TRL', 'TRL'), ('YUD', 'YUD'), ('XSU', 'XSU'), ('ZRN', 'ZRN'), ('XCD', 'XCD'), ('LUC', 'LUC'), ('MZN', 'MZN'), ('SIT', 'SIT'), ('JPY', 'JPY'), ('ESP', 'ESP'), ('AUD', 'AUD'), ('MDL', 'MDL'), ('MRU', 'MRU'), ('SVC', 'SVC'), ('IDR', 'IDR'), ('BGM', 'BGM'), ('WST', 'WST'), ('CSK', 'CSK'), ('ARP', 'ARP'), ('TND', 'TND'), ('UAH', 'UAH'), ('ZMW', 'ZMW'), ('BIF', 'BIF'), ('BYN', 'BYN'), ('XXX', 'XXX'), ('BZD', 'BZD'), ('PES', 'PES'), ('XTS', 'XTS'), ('MTL', 'MTL'), ('CNH', 'CNH'), ('USN', 'USN'), ('ARS', 'ARS'), ('MZM', 'MZM'), ('TTD', 'TTD'), ('EUR', 'EUR'), ('COU', 'COU'), ('KGS', 'KGS'), ('PLZ', 'PLZ'), ('TPE', 'TPE'), ('XPF', 'XPF'), ('VES', 'VES'), ('PAB', 'PAB'), ('MVP', 'MVP'), ('PKR', 'PKR'), ('CRC', 'CRC'), ('ALK', 'ALK'), ('SLE', 'SLE'), ('ZAR', 'ZAR'), ('THB', 'THB'), ('USS', 'USS'), ('XAU', 'XAU'), ('GQE', 'GQE'), ('SRD', 'SRD'), ('MAF', 'MAF'), ('GBP', 'GBP'), ('DDM', 'DDM'), ('EEK', 'EEK'), ('MRO', 'MRO'), ('BGL', 'BGL'), ('BEF', 'BEF'), ('UGX', 'UGX'), ('QAR', 'QAR'), ('MNT', 'MNT'), ('AOK', 'AOK'), ('MOP', 'MOP'), ('CDF', 'CDF'), ('DKK', 'DKK'), ('AON', 'AON'), ('EGP', 'EGP'), ('PEI', 'PEI'), ('IRR', 'IRR'), ('XPD', 'XPD'), ('ADP', 'ADP'), ('RHD', 'RHD'), ('TMT', 'TMT'), ('SEK', 'SEK'), ('MKN', 'MKN'), ('XEU', 'XEU'), ('GIP', 'GIP'), ('STN', 'STN'), ('GYD', 'GYD'), ('XFO', 'XFO'), ('DEM', 'DEM'), ('USD', 'USD'), ('XOF', 'XOF'), ('BTN', 'BTN'), ('XFU', 'XFU'), ('LYD', 'LYD'), ('BAN', 'BAN'), ('ESB', 'ESB'), ('RUR', 'RUR'), ('ARA', 'ARA'), ('XBD', 'XBD'), ('MDC', 'MDC'), ('TWD', 'TWD'), ('SHP', 'SHP'), ('LTT', 'LTT'), ('XDR', 'XDR'), ('LVR', 'LVR'), ('SKK', 'SKK'), ('HRK', 'HRK'), ('HUF', 'HUF'), ('NIC', 'NIC'), ('SAR', 'SAR'), ('AOA', 'AOA'), ('CLP', 'CLP'), ('XAF', 'XAF'), ('LBP', 'LBP'), ('YER', 'YER'), ('ZRZ', 'ZRZ'), ('PEN', 'PEN'), ('BRN', 'BRN'), ('GWE', 'GWE'), ('XUA', 'XUA'), ('VUV', 'VUV'), ('UYI', 'UYI'), ('BUK', 'BUK'), ('BWP', 'BWP'), ('PGK', 'PGK'), ('JOD', 'JOD'), ('XRE', 'XRE'), ('CVE', 'CVE'), ('LTL', 'LTL'), ('BGO', 'BGO'), ('KZT', 'KZT'), ('ETB', 'ETB'), ('GHC', 'GHC'), ('XPT', 'XPT'), ('NGN', 'NGN'), ('BRZ', 'BRZ'), ('SZL', 'SZL'), ('IQD', 'IQD'), ('UYP', 'UYP'), ('BDT', 'BDT'), ('AED', 'AED'), ('KRO', 'KRO'), ('MCF', 'MCF'), ('BRL', 'BRL'), ('ESA', 'ESA'), ('CLE', 'CLE'), ('BYR', 'BYR'), ('AFN', 'AFN'), ('KWD', 'KWD'), ('MGF', 'MGF'), ('CLF', 'CLF'), ('BRB', 'BRB'), ('PHP', 'PHP'), ('SDP', 'SDP'), ('SRG', 'SRG'), ('ISK', 'ISK'), ('CUC', 'CUC'), ('TJS', 'TJS'), ('ARM', 'ARM'), ('CYP', 'CYP'), ('RON', 'RON'), ('VNN', 'VNN'), ('CHE', 'CHE'), ('FJD', 'FJD'), ('AFA', 'AFA'), ('CAD', 'CAD'), ('ILP', 'ILP'), ('ZAL', 'ZAL'), ('MVR', 'MVR'), ('BOV', 'BOV'), ('NOK', 'NOK'), ('DOP', 'DOP'), ('MGA', 'MGA'), ('MXV', 'MXV'), ('ZWL', 'ZWL'), ('GRD', 'GRD'), ('PTE', 'PTE'), ('BEC', 'BEC'), ('MAD', 'MAD'), ('PLN', 'PLN'), ('SBD', 'SBD'), ('ALL', 'ALL'), ('UAK', 'UAK'), ('BRR', 'BRR'), ('ATS', 'ATS'), ('ZWR', 'ZWR'), ('BEL', 'BEL'), ('SDD', 'SDD'), ('BRC', 'BRC'), ('JMD', 'JMD'), ('MMK', 'MMK'), ('ITL', 'ITL'), ('TRY', 'TRY'), ('NZD', 'NZD'), ('RSD', 'RSD'), ('LUL', 'LUL'), ('BOL', 'BOL'), ('ERN', 'ERN'), ('XBC', 'XBC'), ('ECV', 'ECV'), ('VEB', 'VEB'), ('BSD', 'BSD'), ('STD', 'STD'), ('CHW', 'CHW'), ('UYW', 'UYW'), ('SLL', 'SLL'), ('COP', 'COP'), ('KRW', 'KRW'), ('HRD', 'HRD'), ('BAM', 'BAM'), ('LAK', 'LAK'), ('RUB', 'RUB'), ('SDG', 'SDG'), ('SUR', 'SUR'), ('LRD', 'LRD'), ('TZS', 'TZS'), ('AZN', 'AZN'), ('BMD', 'BMD'), ('HTG', 'HTG'), ('ILS', 'ILS'), ('NPR', 'NPR'), ('RWF', 'RWF'), ('KES', 'KES'), ('GEL', 'GEL'), ('OMR', 'OMR'), ('MUR', 'MUR'), ('MZE', 'MZE'), ('SCR', 'SCR'), ('FRF', 'FRF'), ('BHD', 'BHD'), ('GNF', 'GNF'), ('TJR', 'TJR'), ('ZMK', 'ZMK'), ('LKR', 'LKR'), ('ANG', 'ANG'), ('FKP', 'FKP'), ('BND', 'BND'), ('BBD', 'BBD'), ('MTP', 'MTP'), ('CUP', 'CUP'), ('ROL', 'ROL'), ('GNS', 'GNS'), ('SYP', 'SYP'), ('CHF', 'CHF'), ('GWP', 'GWP'), ('UYU', 'UYU'), ('ILR', 'ILR'), ('XBA', 'XBA'), ('BOB', 'BOB'), ('MKD', 'MKD'), ('SGD', 'SGD'), ('MLF', 'MLF'), ('MYR', 'MYR'), ('AOR', 'AOR'), ('ZWD', 'ZWD'), ('TOP', 'TOP'), ('UZS', 'UZS'), ('PYG', 'PYG'), ('VED', 'VED'), ('YUM', 'YUM'), ('NIO', 'NIO'), ('KPW', 'KPW'), ('IEP', 'IEP'), ('NAD', 'NAD'), ('AZM', 'AZM'), ('GMD', 'GMD'), ('KRH', 'KRH'), ('BGN', 'BGN'), ('XBB', 'XBB'), ('LVL', 'LVL'), ('ARL', 'ARL'), ('UGS', 'UGS'), ('MXP', 'MXP'), ('TMM', 'TMM'), ('AWG', 'AWG'), ('GTQ', 'GTQ'), ('BRE', 'BRE'), ('VEF', 'VEF'), ('BYB', 'BYB'), ('FIM', 'FIM'), ('GEK', 'GEK'), ('HNL', 'HNL')], default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
