# Generated by Django 4.1.1 on 2022-12-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0009_category_alter_settings_currency_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('FD', 'Food & Drinks'), ('SG', 'Shopping'), ('RT', 'Rent'), ('TL', 'Travel'), ('SS', 'Sports'), ('IT', 'Internet'), ('IS', 'Investments'), ('ET', 'Entertainment'), ('SY', 'Study'), ('VE', 'Vehicle'), ('TN', 'Transportation'), ('GS', 'Groceries'), ('KS', 'Kids'), ('GT', 'Gifts'), ('GL', 'General'), ('FL', 'Fuel'), ('HS', 'Holidays')], max_length=2),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.category'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('NZD', 'NZD'), ('LSL', 'LSL'), ('XPF', 'XPF'), ('XDR', 'XDR'), ('TRY', 'TRY'), ('RON', 'RON'), ('LVR', 'LVR'), ('CRC', 'CRC'), ('NAD', 'NAD'), ('MZN', 'MZN'), ('GRD', 'GRD'), ('XPD', 'XPD'), ('BYB', 'BYB'), ('COU', 'COU'), ('DKK', 'DKK'), ('LTT', 'LTT'), ('VEF', 'VEF'), ('GNS', 'GNS'), ('VED', 'VED'), ('UAK', 'UAK'), ('RHD', 'RHD'), ('XPT', 'XPT'), ('NLG', 'NLG'), ('BAM', 'BAM'), ('DOP', 'DOP'), ('SDD', 'SDD'), ('FKP', 'FKP'), ('BEF', 'BEF'), ('UGS', 'UGS'), ('IQD', 'IQD'), ('AON', 'AON'), ('GTQ', 'GTQ'), ('ZAR', 'ZAR'), ('ATS', 'ATS'), ('CNX', 'CNX'), ('DEM', 'DEM'), ('ISJ', 'ISJ'), ('MDC', 'MDC'), ('ZWR', 'ZWR'), ('STN', 'STN'), ('YUN', 'YUN'), ('PGK', 'PGK'), ('AFA', 'AFA'), ('BMD', 'BMD'), ('ILR', 'ILR'), ('BHD', 'BHD'), ('BEC', 'BEC'), ('NIC', 'NIC'), ('XXX', 'XXX'), ('NOK', 'NOK'), ('BOV', 'BOV'), ('XAF', 'XAF'), ('CNH', 'CNH'), ('LAK', 'LAK'), ('GNF', 'GNF'), ('HTG', 'HTG'), ('HUF', 'HUF'), ('SIT', 'SIT'), ('HRD', 'HRD'), ('BYN', 'BYN'), ('TJR', 'TJR'), ('ZRN', 'ZRN'), ('ZRZ', 'ZRZ'), ('DZD', 'DZD'), ('AZM', 'AZM'), ('BGL', 'BGL'), ('HNL', 'HNL'), ('SDP', 'SDP'), ('WST', 'WST'), ('ISK', 'ISK'), ('NGN', 'NGN'), ('VNN', 'VNN'), ('KWD', 'KWD'), ('CNY', 'CNY'), ('THB', 'THB'), ('CZK', 'CZK'), ('KHR', 'KHR'), ('GEK', 'GEK'), ('LKR', 'LKR'), ('BSD', 'BSD'), ('TPE', 'TPE'), ('BND', 'BND'), ('CSD', 'CSD'), ('XFU', 'XFU'), ('BTN', 'BTN'), ('BGO', 'BGO'), ('YER', 'YER'), ('BAN', 'BAN'), ('ERN', 'ERN'), ('GMD', 'GMD'), ('LUC', 'LUC'), ('MZE', 'MZE'), ('CUC', 'CUC'), ('BAD', 'BAD'), ('BGN', 'BGN'), ('PYG', 'PYG'), ('DDM', 'DDM'), ('SEK', 'SEK'), ('UYW', 'UYW'), ('EGP', 'EGP'), ('AOA', 'AOA'), ('LVL', 'LVL'), ('IRR', 'IRR'), ('GQE', 'GQE'), ('UYI', 'UYI'), ('XEU', 'XEU'), ('XAU', 'XAU'), ('GIP', 'GIP'), ('RUB', 'RUB'), ('BEL', 'BEL'), ('XSU', 'XSU'), ('NPR', 'NPR'), ('USS', 'USS'), ('MXP', 'MXP'), ('ZMK', 'ZMK'), ('AZN', 'AZN'), ('SBD', 'SBD'), ('MXN', 'MXN'), ('MGF', 'MGF'), ('RUR', 'RUR'), ('CVE', 'CVE'), ('CAD', 'CAD'), ('MVR', 'MVR'), ('YDD', 'YDD'), ('LBP', 'LBP'), ('RWF', 'RWF'), ('CSK', 'CSK'), ('TMM', 'TMM'), ('TWD', 'TWD'), ('MAD', 'MAD'), ('XOF', 'XOF'), ('MNT', 'MNT'), ('MKN', 'MKN'), ('UYU', 'UYU'), ('EEK', 'EEK'), ('XTS', 'XTS'), ('GYD', 'GYD'), ('MMK', 'MMK'), ('ALK', 'ALK'), ('UGX', 'UGX'), ('SCR', 'SCR'), ('AOK', 'AOK'), ('XCD', 'XCD'), ('CHE', 'CHE'), ('PTE', 'PTE'), ('COP', 'COP'), ('CHW', 'CHW'), ('MAF', 'MAF'), ('ADP', 'ADP'), ('EUR', 'EUR'), ('LUL', 'LUL'), ('PHP', 'PHP'), ('ZAL', 'ZAL'), ('MDL', 'MDL'), ('OMR', 'OMR'), ('GWE', 'GWE'), ('DJF', 'DJF'), ('VUV', 'VUV'), ('BRC', 'BRC'), ('HKD', 'HKD'), ('MYR', 'MYR'), ('BGM', 'BGM'), ('RSD', 'RSD'), ('KPW', 'KPW'), ('SYP', 'SYP'), ('CLE', 'CLE'), ('FJD', 'FJD'), ('MCF', 'MCF'), ('YUR', 'YUR'), ('ITL', 'ITL'), ('MVP', 'MVP'), ('AUD', 'AUD'), ('BYR', 'BYR'), ('QAR', 'QAR'), ('KZT', 'KZT'), ('XBD', 'XBD'), ('SRG', 'SRG'), ('XFO', 'XFO'), ('ESA', 'ESA'), ('SUR', 'SUR'), ('BBD', 'BBD'), ('SRD', 'SRD'), ('IEP', 'IEP'), ('ZWL', 'ZWL'), ('BDT', 'BDT'), ('KMF', 'KMF'), ('TND', 'TND'), ('SHP', 'SHP'), ('ANG', 'ANG'), ('CLF', 'CLF'), ('CLP', 'CLP'), ('JOD', 'JOD'), ('STD', 'STD'), ('TJS', 'TJS'), ('YUD', 'YUD'), ('SDG', 'SDG'), ('VES', 'VES'), ('GWP', 'GWP'), ('ESP', 'ESP'), ('HRK', 'HRK'), ('KRW', 'KRW'), ('LTL', 'LTL'), ('MUR', 'MUR'), ('INR', 'INR'), ('SAR', 'SAR'), ('USD', 'USD'), ('TZS', 'TZS'), ('SSP', 'SSP'), ('AWG', 'AWG'), ('KES', 'KES'), ('MWK', 'MWK'), ('VEB', 'VEB'), ('PLZ', 'PLZ'), ('ARP', 'ARP'), ('FIM', 'FIM'), ('BRB', 'BRB'), ('ZWD', 'ZWD'), ('UAH', 'UAH'), ('MTL', 'MTL'), ('AED', 'AED'), ('AOR', 'AOR'), ('MTP', 'MTP'), ('KRO', 'KRO'), ('UZS', 'UZS'), ('XUA', 'XUA'), ('PES', 'PES'), ('GBP', 'GBP'), ('ESB', 'ESB'), ('BOL', 'BOL'), ('BOB', 'BOB'), ('BRL', 'BRL'), ('CHF', 'CHF'), ('KRH', 'KRH'), ('BRZ', 'BRZ'), ('MRU', 'MRU'), ('CUP', 'CUP'), ('ETB', 'ETB'), ('BZD', 'BZD'), ('MGA', 'MGA'), ('CYP', 'CYP'), ('SOS', 'SOS'), ('BRN', 'BRN'), ('BRE', 'BRE'), ('MXV', 'MXV'), ('PAB', 'PAB'), ('ROL', 'ROL'), ('ZMW', 'ZMW'), ('XRE', 'XRE'), ('MOP', 'MOP'), ('FRF', 'FRF'), ('GHS', 'GHS'), ('SGD', 'SGD'), ('BIF', 'BIF'), ('SZL', 'SZL'), ('ECS', 'ECS'), ('USN', 'USN'), ('XBC', 'XBC'), ('VND', 'VND'), ('LUF', 'LUF'), ('AFN', 'AFN'), ('ARA', 'ARA'), ('BOP', 'BOP'), ('BUK', 'BUK'), ('BRR', 'BRR'), ('MRO', 'MRO'), ('KGS', 'KGS'), ('ALL', 'ALL'), ('PKR', 'PKR'), ('NIO', 'NIO'), ('IDR', 'IDR'), ('SLL', 'SLL'), ('TMT', 'TMT'), ('SLE', 'SLE'), ('JMD', 'JMD'), ('SVC', 'SVC'), ('LRD', 'LRD'), ('MZM', 'MZM'), ('TTD', 'TTD'), ('UYP', 'UYP'), ('TRL', 'TRL'), ('XBB', 'XBB'), ('KYD', 'KYD'), ('CDF', 'CDF'), ('AMD', 'AMD'), ('BWP', 'BWP'), ('ILS', 'ILS'), ('PEI', 'PEI'), ('GHC', 'GHC'), ('ARL', 'ARL'), ('PLN', 'PLN'), ('ECV', 'ECV'), ('ARM', 'ARM'), ('ILP', 'ILP'), ('GEL', 'GEL'), ('LYD', 'LYD'), ('PEN', 'PEN'), ('XBA', 'XBA'), ('ARS', 'ARS'), ('JPY', 'JPY'), ('SKK', 'SKK'), ('MLF', 'MLF'), ('MKD', 'MKD'), ('YUM', 'YUM'), ('XAG', 'XAG'), ('TOP', 'TOP')], default='USD', max_length=3),
        ),
    ]
