# Generated by Django 4.0.5 on 2022-06-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_comment_bid_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
